import random

# random.randrange(3)
# # random.randrange(0, 10, 2)

# random.randrange(1, 3)
# random.randrange(0, 10, 2)
# list
# ["蘋果", "香蕉", "葡萄"]
# list裡能再塞一個list
# len([])
# len(["蘋果"])
# len(["a", "b"])
# len([1, 2, 3])

# print(len)
# L = [1, 2, 3, "Hello", "world", [4, 5, 6]]
# print(L[6])
# l = [0, 1, 2, 3, 4, 5, 6]
# l[0:5:2]
# l[::3]
# print(l[-1])

# l = ["a", "b", "c"]
# for index in range(len(l)):
#     print(l[index])

l = ["a", "b", "c"]
for element in l:
    print(element)
