import turtle

# turtle.forward(150)  #int or float
# turtle.backward(90)  #int or float
# turtle.right(900)  #int or float
# turtle.left(800)  #int or float
# turtle.done()  # 讓視窗綁持顯示

# import turtle
# # move the turtle
# turtle.forward(150)
# turtle.left(90)
# turtle.forward(150)
# turtle.left(90)
# turtle.forward(150)
# turtle.left(90)
# turtle.forward(150)
# turtle.left(90)
# turtle.down()

# turtle.forward(150)
# turtle.left(60)
# turtle.forward(150)
# turtle.left(60)
# turtle.forward(150)
# turtle.left(60)
# turtle.forward(150)
# turtle.left(60)
# turtle.forward(150)
# turtle.left(60)
# turtle.forward(150)
# turtle.left(60)
# turtle.down()
# for i in range(2, 6):
#     print(i)
# for 迴圈變數 in range(執行次數):
# 要重複的程式
# 重複執行程式
# 從 起數職 數到 終止值 為止
# 每次一 變化值 遞增,不包含終止值
for i in range(2, 10, 2):
    print(i)