 #def 是宣告函數
# def hello():
#      print("hello")
# hello()

# def hello(ee2):
#    print("hello" + str(ee2))
# hello(" 宇呈")
# hello(" BenBen")
# hello(" BenBenBen")

# # 函數my_min是判斷最小
# def my_min(a,b):
#     if a < b :
#         return a
#     else:
#         return b
# my_min(1,2)

# a=1
# b=2
# def my_min(a,b):
#    a = my_min(a,b )
# print("my_min:" + str(a))

# length = 5
# def calculate_square_area():
#    area = length**2
#    print("⾯積是", area)
# calculate_square_area()

# length = 5
# def calculate_square_area():
#    area = length**2
#    print("⾯積是", area)


# length = 10
# calculate_square_area()

# length = 5
# area = 3.14 * 10**2


# def calculate_square_area():
#    area = length**2
# calculate_square_area()
# print("⾯積是", area)

# length = 5
# area = 3.14 * 10**2


# def calculate_square_area():
#    print("⾯積是", area)
#    area = length**2
#    print("⾯積是", area)

# calculate_square_area()

# def add(n1,n2):
#     x=n1+n2
#     return x
# value=add(1,8)
# print(value)

# def mul(x,y):
#     result = x*y
#     return result

# length = 5
# def calculate_square_area():
#    area = length**2
#    length = 10
   
# calculate_square_area()
# print("⾯積是", area)

# length = 5
# area = 3.14 * 10**2
# def calculate_square_area():
#    area = length**2
# calculate_square_area()
# print("⾯積是", area)

def mul(a,b,c):
    x=(a*b)/c
    print(x)
    return x

mul(100,200,40000)

    